### ISSUE TITLE
User Story - Sign up & log in

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#1]
As a **new user** I can **sign up** so that **I can have my own account and use the full feature set of the website**.

#### Acceptance Criteria:
- User can use a sign up form
- User can provide a username, email address and password to use as log in credentials
- User is redirected to a log in page after sign up

#### Tasks:
- [x] Create sign up form, view, url, and template with redirect to log in view
- [x] Create log in view, url and template
- [x] Create logout view and url
