### ISSUE TITLE
User Story - Post

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#10]
As a **user** I can **create a new post** so that **I can share something with my followers**.

#### Acceptance Criteria:
- A logged in user can write a post
- The post is displayed on the user's profile
- The post is shown on the feed page of other users that follow the author

#### Tasks:
- [x] Create the post model
- [x] Create a post form
- [x] Create the new post url, view, and template
