### ISSUE TITLE
User Story - Post Image

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#11]
As a **user** I can **add an image to my post** so that **I can share an image with my followers**.

#### Acceptance Criteria:
- User can add upload an optional image to their post
- The image is cropped and resized appropriately
- The image is shown as part of the users post if included

#### Tasks:
- [x] Add image field to post model
- [x] Add file input to post form for image
- [x] Display image with the post where shown
