### ISSUE TITLE
User Story - Post Link

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#12]
As a **user** I can **add a link to a website to my post** so that **I can share a website with my followers**.

#### Acceptance Criteria:
- User can add an optional url to their post
- The url is turned into a working hyperlink that opens in a new tab
- The url is shown as part of the users post if included

#### Tasks:
- [x] Add text field to post model for url
- [x] Add text input to post form for url
- [x] Display url as working hyperlink with the post where shown
