### ISSUE TITLE
User Story - Like Post

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#13]
As a **user** I can **like my own or someone else's post** so that **I can show my support**.

#### Acceptance Criteria:
- User can add like or unlike a post
- The like count is displayed on the post to all users
- The like button updates when clicked to represent liked status

#### Tasks:
- [x] Add like many to many field to post model
- [x] Add like post url and view
- [x] Add form with button to the post where the user can submit their like
- [x] Display like count on post
- [x] Current like status shown to user
