### ISSUE TITLE
User Story - Delete Post

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#14]
As a **user** I can **delete my own posts** so that **I can remove them from my profile if necessary**.

#### Acceptance Criteria:
- The user can delete their post
- The user can't delete anyone else's posts
- The user is asked for confirmation before deleting a post

#### Tasks:
- [x] Add delete post url and view
- [x] Add modal for post deletion confirmation
- [x] Delete post view will `.delete()` post
