### ISSUE TITLE
User Story - Delete Reply

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#18]
As a **user** I can **delete my replies** so that **I can remove them if I want**.

#### Acceptance Criteria:
- The user can delete their reply
- The user can't delete anyone else's replies
- The user is asked for confirmation before deleting a reply

#### Tasks:
- [x] Add delete reply url and view
- [x] Add modal for reply deletion confirmation
- [x] Delete reply view will .delete() reply object
