### ISSUE TITLE
User Story - Hide Reply

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#19]
As a **user** I can **hide a reply to my post** so that **it can be hidden from other users if inappropriate or irrelevant**.

#### Acceptance Criteria:
- The user can hide a reply on their post
- The user is asked for confirmation
- The user can only hide replies on their own posts
- The author of the hidden reply is notified

#### Tasks:
- [x] Add hidden boolean field to reply model
- [x] Add hide reply url and view
- [x] Add button to hide reply if the logged in user is the post author
- [x] Add modal for confirmation
