### ISSUE TITLE
User Story - Tagging

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#21]
As a **user** I can **tag other users in my posts, replies and messages** so that **I can link directly to their profile**.

#### Acceptance Criteria:
- The user can tag a user using ~ followed by the username of the target user when writing a post, reply or message
- This is turned into a link that directs to the target user's profile page
- The target user is notified when mentioned/tagged (excluding when tagged in messages)
- User can mark posts containing mentions as read

#### Tasks:
- [x] Use JavaScript to turn `~username` into a link that targets the correct user's profile page
- [x] Add mentions view, url and template
- [x] Filter reply, message and post objects using `.filter(username=taggeduser)`
- [x] Add read many to many field to post and reply models
- [x] Add mark read url and view
