### ISSUE TITLE
User Story - Read PM

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#24]
As a **user** I can **have a message inbox** so that **I can read my private messages**.

#### Acceptance Criteria:
- The user can read their private messages
- The user can only read their private messages and no one else's
- The user is notified of a new unread private message
- Messages can be marked as read
- The sender of a message can see if their message has been read by the recipient

#### Tasks:
- [x] Create inbox view, url, and template
- [x] Add read boolean field to message model
- [x] Add mark as read button to message
- [x] Add text to message sender's sent messages page if message has been read
