### ISSUE TITLE
User Story - Delete Message

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#26]
As a **user** I can **delete a message** so that **that I keep my inbox clear and/or remove no longer useful messages**.

#### Acceptance Criteria:
- The user can delete a message
- The user can only delete their messages
- The user is asked for confirmation before deletion
- A deleted message is only deleted/hidden from the user that wants to delete it (sender or recipient)

#### Tasks:
- [x] Add `sender_delete` and `recipient_delete` boolean field to message model
- [x] If both fields are true message is deleted
- [x] Add delete message url and view
- [x] Add delete message button to message
- [x] Add modal for deletion confirmation
