### ISSUE TITLE
User Story - Delete Account

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#29]
As a **user** I can **delete my account** so that **I can leave the website and remove all my content**.

#### Acceptance Criteria:
- The user can delete their account
- The user is asked for confirmation before account deletion
- All content by the user is removed when their account is deleted

#### Tasks:
- [x] Add delete account button with confirmation modal
- [x] Add delete account url, and view
- [x] Use `on_delete=models.CASCADE` on post, reply and message model to ensure the delete user's content is also deleted
