### ISSUE TITLE
User Story - Reset Password

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#31]
As a **user** I can **reset my password** so that **I can still log in if I have forgotten my password**.

#### Acceptance Criteria:
- The user can reset their password from the log in screen
- Email confirmation is required

#### Tasks:
- [x] Include `django.contrib.auth.urls` in the main urls.py file
- [x] Add my own `password_reset_complete.html`
- [x] Add my own `password_reset_confirm.html`
- [x] Add my own `password_reset_done.html`
- [x] Add my own `password_reset_form.html`
