### ISSUE TITLE
User Story - Moderator Delete/Okay

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#33]
As a **moderator** I can **delete or mark okay a reported item** so that **it can either be deleted or removed from the reported items list where appropriate**.

#### Acceptance Criteria:
- Reported items can be marked as okay or deleted
- If an item is marked as okay it is removed from the moderation list
- If an item is deleted the responsible user gains a strike

#### Tasks:
- [x] Add view and url to mark objects as okay (remove reported field)
- [x] Add strikes integer field to user model
- [x] Add view and url to delete object and add 1 to user strike field
