### ISSUE TITLE
User Story - Moderator Ban/Unban User

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#36]
As a **moderator** I can **ban or unban a user** so that **they can be banned or unbanned if necessary**.

#### Acceptance Criteria:
- A moderator can ban a user
- Confirmation is required before a user is banned
- A moderator can unban a banned user
- Ban status is shown to the moderator
- Only a moderator can do this

#### Tasks:
- [x] Create ban user view and url
- [x] Add ban or unban button to user on moderation page
- [x] Use `user.is_active = False` to ban a user
- [x] Use `user.is_active = True` to unban a user
