### ISSUE TITLE
User Story - Search

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#4]
As a **user** I can **search Squigl** so that **I can find users, posts and replies that I am looking for**.

#### Acceptance Criteria:
- Search form takes a query and returns a list of results which the user can filter by category

#### Tasks:
- [x] Create search form
- [x] User query from search form to filter the database
- [x] Render results as context into template
- [x] Create search page view, url, and template
