### ISSUE TITLE
User Story - Avatar

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#5]
As a **user** I can **upload an avatar** so that **it can represent me as a user**.

#### Acceptance Criteria:
- User can upload an avatar
- Avatar is cropped to be square resized appropriately 

#### Tasks:
- [x] Add avatar image field to user model
- [x] Add file input to user profile form
- [x] Show avatar where necessary (on profile, on posts etc)
