### ISSUE TITLE
User Story - User URL

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#6]
As a **user** I can **add a link to my profile** so that **I can share something important to me or another website relevant to my account**.

#### Acceptance Criteria:
- User can add a url to their profile
- The url is a working hyperlink shown on their profile
- When clicked it opens the webpage in a new tab

#### Tasks:
- [x] Add url text field to user model
- [x] Add text input to user profile form for url
- [x] Show url on user profile page as a working link
