### ISSUE TITLE
User Story - About/Bio

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#7]
As a **user** I can **add a short description to my profile** so that **other users can find out more about me**.

#### Acceptance Criteria:
- User can add, edit, and remove a short description to their profile page
- This is displayed to all users

#### Tasks:
- [x] Add about text field to user model
- [x] Add text input to user profile form for the about text
- [x] Show about on user profile page
