### ISSUE TITLE
User Story - Profile Background

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#8]
As a **user** I can **add an image as a background to my profile** so that **I can further customise my profile**.

#### Acceptance Criteria:
- The user can add/edit/remove an image to be used as a background on their profile
- The image is cropped, appropriately resized, and maintains the correct aspect ratio at all times

#### Tasks:
- [x] Add background image field to user model
- [x] Add file input to user profile form for background image
- [x] Show background image on user profile page
