### ISSUE TITLE
User Story - Follow / Unfollow

### ISSUE THREAD

**Issue by paulio11** [paulio11/project-4#9]
As a **user** I can **follow or unfollow other users** so that **their posts appear in my feed**.

#### Acceptance Criteria:
- A logged in user can either follow or unfollow a user
- Current following status is shown on a user's profile page
- Followed user's posts appear on the logged in users feed

#### Tasks:
- [x] Use following field in the user model to filter posts
- [x] Pass filtered posts to feed view and show on template
- [x] Add form to a user's profile page which will either follow or unfollow the user
- [x] Add url and view for following functionality that adds or removes a user from the logged in users following field.
